### ISSUE TITLE
Login error - Try signing in with a different account

### ISSUE THREAD

**Issue by monty23monty** [vZDC-ARTCC/website#13]
### Your Vatsim CID

1560689

### Description

When trying to login, I am redirected to https://vzdc.org/api/auth/signin?error=OAuthCallback

This asks me to login with a different account.

When asked to login with a different account, it works as expected.
![image](https://github.com/vZDC-ARTCC/website/assets/74265105/1ffaaa66-ec83-4944-95e7-c92990b5ea0e)

### Minimal Reproduction

Try to login as usual to the website.

### Validation

- [X] I have searched open/closed issues and did not find any similar bugs

**Comment by Vainnor** [comment]
This is a VATUSA bug as far as I know. Seems to be fixed with recent VATUSA API optimizations. Closing for now.
