### ISSUE TITLE
Training Ticket Common Mistakes Form

### ISSUE THREAD

**Issue by Vainnor** [vZDC-ARTCC/website#17]
### Your Vatsim CID

1652726

### Description

When creating a common mistake, if you do not input anything into the form and click save, it redrects you to a white page.

### Minimal Reproduction

Create new common mistakes. Give it a name and click save.

### Validation

- [X] I have searched open/closed issues and did not find any similar bugs

**Comment by harryxu2626** [comment]
Fixed in 1.0.12
