### ISSUE TITLE
Lesson not found in training session history

### ISSUE THREAD

**Issue by monty23monty** [vZDC-ARTCC/website#19]
### Your Vatsim CID

1560689

### Description

When using training history to look up a students tickets, when I clicked on one to view it, the message Lesson not found was shown

### Minimal Reproduction

Search for a student, select a ticket.

i.e. Akil Gunn, 2-2-1

### Additional info

Tickets appear normally when looking in the training sessions tab and clicking

### Validation

- [X] I have searched open/closed issues and did not find any similar bugs

**Comment by Vainnor** [comment]
Known bug already fixed
