### ISSUE TITLE
Purge Assistant separate home/visiting controllers

### ISSUE THREAD

**Issue by yanjz124** [vZDC-ARTCC/website#20]
### Your Vatsim CID

1340265

### What do you suggest?

Ability to filter home and visiting controllers on the purge list

### Why do you need that?

Make my life easier

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by harryxu2626** [comment]
Implemented change. Awaiting testing and will be implemented next patch.
