### ISSUE TITLE
Filter for Training Sessions doesn't seem to work

### ISSUE THREAD

**Issue by jackson-smith-ZDC** [vZDC-ARTCC/website#21]
### Your Vatsim CID

1471203

### Description

Curious on looking at sessions certain trainers are submitting on the site. Went to filter and selected the trainer column, then selected contains, then the trainer name, and nothing happened. Tried hitting enter and refreshing the site.  

### Minimal Reproduction

Start point - https://vzdc.org/training/sessions

1) Select "filters"
2) Under column select "trainer"
3) Under operator select "contains"
4) Typed "Jackson" in the value 
I also tried the following values:
Jackson Smith
Smith
Jackson Smith (1471203)
1471203

### Validation

- [X] I have searched open/closed issues and did not find any similar bugs

**Comment by harryxu2626** [comment]
Found the issue, will be fixed next patch.
