### ISSUE TITLE
View preview of common mistakes when creating a ticket

### ISSUE THREAD

**Issue by monty23monty** [vZDC-ARTCC/website#23]
### Your Vatsim CID

1560689

### What do you suggest?

I would like a way to preview what a common mistake says inside of it to make sure it is relevant to the ticket im making. For example a Modal that appears to show the content of the mistake when you click on it in this state: 
![image](https://github.com/user-attachments/assets/841c8289-5d03-4bb8-b367-ae25535556c2)

### Why do you need that?

To help to check a common mistakes relevance to the ticket that im making as some are not named perfectly

### Alternatives

Alternative is to open another tab and look at the mistakes in the Mistakes tab to check.

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by Vainnor** [comment]
I'll think on it.

**Comment by harryxu2626** [comment]
Added a hover tooltip on the common mistakes to preview contents. If this is good I'll push to next.

![image](https://github.com/user-attachments/assets/4c4b05c1-44af-436f-b798-8bc69b9952a0)

![image](https://github.com/user-attachments/assets/4996ca49-af19-4aff-a1d0-86fc961dbd5e)

**Comment by Vainnor** [comment]
> Added a hover tooltip on the common mistakes to preview contents. If this is good I'll push to next.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4c4b05c1-44af-436f-b798-8bc69b9952a0)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4996ca49-af19-4aff-a1d0-86fc961dbd5e)
> 
> 

This is good. Can you just put it into a new branch for me please?

**Comment by Vainnor** [comment]
Done in 1.1.0
