### ISSUE TITLE
Page not found - https://vzdc.org/license.txt

### ISSUE THREAD

**Issue by monty23monty** [vZDC-ARTCC/website#27]
### Your Vatsim CID

1560689

### Description

![image](https://github.com/user-attachments/assets/0a6bc325-949b-4b54-96dc-8e8334aeb546)
The Full licence button redirects to a 404 not found on the url vzdc.org/license.txt

### Minimal Reproduction

Press the Full licence button

### Validation

- [X] I have searched open/closed issues and did not find any similar bugs

**Comment by harryxu2626** [comment]
Should be fixed by linking to the online hosted Apache license page instead of trying to point to the license.txt file
