### ISSUE TITLE
Please rework the roster page so there's no more major/minor

### ISSUE THREAD

**Issue by yanjz124** [vZDC-ARTCC/website#30]
### Your Vatsim CID

1340265

### What do you suggest?

With the major/minor certifications phased out, we should really use the current terminologies on our roster. Many other ARTCCs already have their own ways of doing this.
There can be an unrestricted GND/TWR/APP column mainly to reflect solo certs, but ideally it should automatically reflect the appropriate level based on the controller rating. Currently I have to manually go in and change the endorsements each time someone gets added to the roster.

### Why do you need that?

So we don't look like boomers

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by Vainnor** [comment]
Done in next update

**Comment by Vainnor** [comment]
Done in 1.1.0 update
