### ISSUE TITLE
OI Management/Matrix

### ISSUE THREAD

**Issue by yanjz124** [vZDC-ARTCC/website#31]
### Your Vatsim CID

1340265

### What do you suggest?

It's definitely a low-priority item.
An OI matrix (AA-ZZ) shows which OI is in use by a home controller or a visitor and probably even a hyperlink to the control profile.
OI validation when changing OI in the controller profile, prompting if the OI is already in use or unavailable (OK, FU).
The old site allows lowercase OIs so people can be AB and ab the same time and that shouldn't be allowed.

### Why do you need that?

To make my life easier.

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by Vainnor** [comment]
Also making sure OI's get assigned on first login

**Comment by beabravedude** [comment]
Will be added on next update

**Comment by yanjz124** [comment]
Low priority. Is there any chance we could assign OIs from here or somewhere similar? Like if I could click on a controller's name from a roster like this https://vzdc.org/controllers/roster/home, it leads to the controller management page. There can be a separate field for the OI, and when I click on it, it leads to the OI matrix, and I can click an available OI within the matrix to assign that OI to the controller. I hope this makes sense.

**Comment by beabravedude** [comment]
I can make a drop-down when you click on an operating initial to choose a controller and assign it there.
