### ISSUE TITLE
Implementation of trainee rating or current stage when viewing request for trainers

### ISSUE THREAD

**Issue by jackson-smith-ZDC** [vZDC-ARTCC/website#33]
### Your Vatsim CID

1471203

### What do you suggest?

Under "Trainer Requests" add a column with the trainees VATSIM rating or current stage of training to allow assigning trainees to trainees easier without having to refer to the roster for rating and current stage of training. 

### Why do you need that?

Quality of life request. I don't know every trainees rating just off of their name. 

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by beabravedude** [comment]
Will be added next update.
![image](https://github.com/user-attachments/assets/4f3f0156-394b-4aee-b713-7fc5f7087cc8)
