### ISSUE TITLE
Add Hyperlink to VATUSA Profile on Visitor Application Page

### ISSUE THREAD

**Issue by yanjz124** [vZDC-ARTCC/website#35]
### Your Vatsim CID

1340265

### What do you suggest?

On the visitor application page, add a hyperlink to their VATUSA profile, like [https://www.vatusa.net/mgt/controller/1652726](url). I'm unsure if VATUSA API has one for visiting checklists, but having that checklist on the visiting application page is also nice.

### Why do you need that?

convenience. 

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by Vainnor** [comment]
This would be in then facility admin page correct?

**Comment by yanjz124** [comment]
https://vzdc.org/admin/visitor-applications under individual applications

**Comment by beabravedude** [comment]
This will be marked as a feature in the 1.2.0 update.

**Comment by Vainnor** [comment]
Done in next update
