### ISSUE TITLE
VATUSA Roster Sync INOP

### ISSUE THREAD

**Issue by jackson-smith-ZDC** [vZDC-ARTCC/website#36]
### Your Vatsim CID

1471203

### Description

Roster sync is not syncing. A new trainee is on the roster on the VATUSA site but not on our local site.

https://prnt.sc/d5PpEvaO-OlJ

### Minimal Reproduction

n/a

### Validation

- [X] I have searched open/closed issues and did not find any similar bugs

**Comment by beabravedude** [comment]
Fixed.  Thanks for reporting the bug!
