### ISSUE TITLE
Add recent training sessions to a member's profile page

### ISSUE THREAD

**Issue by jackson-smith-ZDC** [vZDC-ARTCC/website#38]
### Your Vatsim CID

1471203

### What do you suggest?

When selecting a member from the "Controller Management" tab, having recent training sessions (perhaps the last 3-5) displayed and viewable via clicking on them. 

### Why do you need that?

Quality of life without having to switch from "Facility Administration" to "Training Administration."

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by harryxu2626** [comment]
Will be added in the next update
