### ISSUE TITLE
Trainee names in "Trainer Requests" hyperlinked to their vZDC site profile

### ISSUE THREAD

**Issue by jackson-smith-ZDC** [vZDC-ARTCC/website#39]
### Your Vatsim CID

1471203

### What do you suggest?

Ability to have trainees who request a trainer have their names hyperlinked so staff can quickly view their profile to see items such as certifications, dossier logs, and recent training tickets (ref the feature request I just submitted).

### Why do you need that?

Quickly determine what level of trainer is needed for a trainee based on their certifications.

### Validation

- [X] I have searched for other requests and did not find any alike
- [x] I have also checked the roadmap, and this is not planned

**Comment by Vainnor** [comment]
Done in next update
