### ISSUE TITLE
Trainer Assignment Requests shows if a trainee is a home or visiting controller

### ISSUE THREAD

**Issue by jackson-smith-ZDC** [vZDC-ARTCC/website#40]
### Your Vatsim CID

1471203

### What do you suggest?

A way to tell at a glance if a trainee is a visitor or a home controller when viewing Trainer Assignment Requests on the site. Due to staffing restraints, we are mainly focusing on trainer requests for home controllers rather than visitors seeking endorsements, and looking up the trainee name on the roster is annoying.

### Why do you need that?

Efficiency when determining the priority of a trainee who is seeking a trainer. Quality of life.

### Validation

- [X] I have searched for other requests and did not find any alike
- [X] I have also checked the roadmap, and this is not planned

**Comment by Vainnor** [comment]
Done in next update
